import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { fetchFromStrapi } from "./utils/strapiFetch";
import { endpoints } from "./constants/endpoints";
import Navbar from "./components/common/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const {
    data: { navbar },
  } = await fetchFromStrapi(endpoints.GLOBAL);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-orange-50`}
      >
        <Navbar navbarData={navbar} />
        <main>{children}</main>
      </body>
    </html>
  );
}
